### ISSUE TITLE
LLVM测试篇-交叉编译：clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by xijing21** [mollybuild/RISCV-Measurement#1]
按照https://github.com/mollybuild/RISCV-Measurement/blob/master/Build-RISCV-LLVM-and-run-testsuite.md 执行交叉编译的时候，cmake报错：
```
xj@e2ba8bd04169:~/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build$ cmake -DCMAKE_TOOLCHAIN_FILE=/home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/clang_riscv_linux.cmake  -DCMAKE_C_COMPILER="/home/xj/RISCV/llvm-project0/build/bin/clang"  ../test-suite
-- The C compiler identification is Clang 13.0.0
-- The CXX compiler identification is Clang 13.0.0
-- Check for working C compiler: /home/xj/RISCV/llvm-project0/build/bin/clang
-- Check for working C compiler: /home/xj/RISCV/llvm-project0/build/bin/clang -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/home/xj/RISCV/llvm-project0/build/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make cmTC_c5958/fast && /usr/bin/make -f CMakeFiles/cmTC_c5958.dir/build.make CMakeFiles/cmTC_c5958.dir/build
    make[1]: Entering directory '/home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_c5958.dir/testCCompiler.c.o
    /home/xj/RISCV/llvm-project0/build/bin/clang --target=riscv64-unknown-linux-gnu --gcc-toolchain=/home/xj/RISCV/linux/    -o CMakeFiles/cmTC_c5958.dir/testCCompiler.c.o   -c /home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_c5958
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c5958.dir/link.txt --verbose=1
    /home/xj/RISCV/llvm-project0/build/bin/clang --target=riscv64-unknown-linux-gnu --gcc-toolchain=/home/xj/RISCV/linux/    -static  CMakeFiles/cmTC_c5958.dir/testCCompiler.c.o  -o cmTC_c5958
    /home/xj/RISCV/linux/lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: warning: -z relro ignored
    /home/xj/RISCV/linux/lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: unrecognized option '--hash-style=gnu'
    /home/xj/RISCV/linux/lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: use the --help option for usage information
    clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [CMakeFiles/cmTC_c5958.dir/build.make:87: cmTC_c5958] Error 1
    make[1]: Leaving directory '/home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_c5958/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:7 (project)


-- Configuring incomplete, errors occurred!
See also "/home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/CMakeFiles/CMakeOutput.log".
See also "/home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/CMakeFiles/CMakeError.log".

```

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/120767407-bed95580-c54d-11eb-917d-4bf51bfdf7fb.png)

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/120767681-fba54c80-c54d-11eb-95ba-89b3e54549b3.png)
![image](https://user-images.githubusercontent.com/84754181/120767749-111a7680-c54e-11eb-97a6-e3e9203ff1fa.png)
![image](https://user-images.githubusercontent.com/84754181/120768192-78382b00-c54e-11eb-9c80-1c95c1fb5e41.png)

**Comment by mollybuild** [comment]
> 
> 
> 按照https://github.com/mollybuild/RISCV-Measurement/blob/master/Build-RISCV-LLVM-and-run-testsuite.md 执行交叉编译的时候，cmake报错：
> 
> ```
> xj@e2ba8bd04169:~/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build$ cmake -DCMAKE_TOOLCHAIN_FILE=/home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/clang_riscv_linux.cmake  -DCMAKE_C_COMPILER="/home/xj/RISCV/llvm-project0/build/bin/clang"  ../test-suite
> -- The C compiler identification is Clang 13.0.0
> -- The CXX compiler identification is Clang 13.0.0
> -- Check for working C compiler: /home/xj/RISCV/llvm-project0/build/bin/clang
> -- Check for working C compiler: /home/xj/RISCV/llvm-project0/build/bin/clang -- broken
> CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
>   The C compiler
> 
>     "/home/xj/RISCV/llvm-project0/build/bin/clang"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: /home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/CMakeFiles/CMakeTmp
> 
>     Run Build Command(s):/usr/bin/make cmTC_c5958/fast && /usr/bin/make -f CMakeFiles/cmTC_c5958.dir/build.make CMakeFiles/cmTC_c5958.dir/build
>     make[1]: Entering directory '/home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/CMakeFiles/CMakeTmp'
>     Building C object CMakeFiles/cmTC_c5958.dir/testCCompiler.c.o
>     /home/xj/RISCV/llvm-project0/build/bin/clang --target=riscv64-unknown-linux-gnu --gcc-toolchain=/home/xj/RISCV/linux/    -o CMakeFiles/cmTC_c5958.dir/testCCompiler.c.o   -c /home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/CMakeFiles/CMakeTmp/testCCompiler.c
>     Linking C executable cmTC_c5958
>     /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c5958.dir/link.txt --verbose=1
>     /home/xj/RISCV/llvm-project0/build/bin/clang --target=riscv64-unknown-linux-gnu --gcc-toolchain=/home/xj/RISCV/linux/    -static  CMakeFiles/cmTC_c5958.dir/testCCompiler.c.o  -o cmTC_c5958
>     /home/xj/RISCV/linux/lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: warning: -z relro ignored
>     /home/xj/RISCV/linux/lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: unrecognized option '--hash-style=gnu'
>     /home/xj/RISCV/linux/lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: use the --help option for usage information
>     clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
>     make[1]: *** [CMakeFiles/cmTC_c5958.dir/build.make:87: cmTC_c5958] Error 1
>     make[1]: Leaving directory '/home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/CMakeFiles/CMakeTmp'
>     make: *** [Makefile:121: cmTC_c5958/fast] Error 2
> 
> 
> 
> 
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:7 (project)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/CMakeFiles/CMakeOutput.log".
> See also "/home/xj/RISCV/llvm-project0/llvm/projects/test-suite-riscv-build/CMakeFiles/CMakeError.log".
> ```


指定的target是riscv64-unknown-linux-gnu， ld用的是riscv64-unknown-elf，不一致。

**Comment by xijing21** [comment]
重新构建riscv-gnu-toolchain的linux函数库：
```
build$ mkdir linux
build$ cd linux
linux$ ../../configure --prefix=$RISCV/linux
linux$ make linux   # 注意这里是make linux
```
make完之后：
![image](https://user-images.githubusercontent.com/84754181/120782176-5645a500-c55c-11eb-8c8c-1693a02ef205.png)


cmake还是报错：
![image](https://user-images.githubusercontent.com/84754181/120791486-db35bc00-c566-11eb-8bbd-54bfce005f24.png)
    /home/xj/RISCV/linux/lib/gcc/riscv64-unknown-linux-gnu/10.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: cannot find crt1.o: No such file or directory  


解决办法：修改环境变量，在~/.bashrc中的path中添加linux构建目录：~/RISCV/linux/bin  再次cmake就好了
